# Netlify configuration for VibeCoding platform
[build]
  # Explicitly set base directory to root
  base = "."
  
  # Simple build command using npx
  command = "npm install && cd client && npm install && npm run build"
  
  # Directory to deploy (client build output)
  publish = "client/dist"
  
  # Set Node.js version and environment variables
  [build.environment]
    NODE_VERSION = "18.19.0"
    NPM_VERSION = "10.2.3"
    NPM_FLAGS = "--legacy-peer-deps"
    CI = "false"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (you'll need to set these in Netlify dashboard)
# VITE_SUPABASE_URL=your_supabase_url
# VITE_SUPABASE_ANON_KEY=your_supabase_anon_key